name: "AutoPublish"

on:
  push:
    branches:
      - "master"

jobs:
  auto-publish:
    name: "AutoPublish on master"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd"  # v5
      - name: "Automated Release"
        uses: "phips28/gh-action-bump-version@215e27a882516826c59df7f09da8c67d5f375cbd"  # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444  # v5
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: "Install dependencies"
        run: npm install
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
